export function TwoSidesSection() {
  return (
    <section className="bg-zinc-950 px-6 py-32">
      <div className="mx-auto max-w-5xl">
        <p className="text-xs text-white/30 uppercase tracking-[0.2em] mb-4 text-center">
          Two sides of one trade
        </p>
        <p className="font-display text-4xl md:text-5xl text-white text-center mb-20 leading-tight">
          LP-D is not charity.<br />
          <span className="italic text-violet-300">It is a position.</span>
        </p>

        <div className="grid md:grid-cols-2 gap-px bg-white/5 rounded-2xl overflow-hidden">
          <div className="bg-zinc-950 px-8 py-10">
            <p className="text-xs text-emerald-400/60 uppercase tracking-[0.2em] mb-5">LP-Y holder</p>
            <p className="font-display text-2xl text-white mb-4 leading-snug">
              Earns fees.<br />
              <span className="text-white/40">Carries zero price risk.</span>
            </p>
            <p className="text-sm text-white/40 leading-relaxed">
              LP-Y earns its configured share of all swap fees generated by the position. If the LP exits
              and price has moved against them, the IL is drawn from the LP-D vault —
              not from their principal. Their fees are theirs. Their principal is intact.
            </p>
            <div className="mt-6 flex gap-2">
              <span className="rounded-full border border-emerald-500/20 bg-emerald-500/5 px-3 py-1 text-xs text-emerald-400">
                fee share (configurable)
              </span>
              <span className="rounded-full border border-emerald-500/20 bg-emerald-500/5 px-3 py-1 text-xs text-emerald-400">
                $0 IL
              </span>
            </div>
          </div>

          <div className="bg-zinc-950 px-8 py-10">
            <p className="text-xs text-violet-400/60 uppercase tracking-[0.2em] mb-5">LP-D holder (the project)</p>
            <p className="font-display text-2xl text-white mb-4 leading-snug">
              Earns fees too.<br />
              <span className="text-white/40">Collateral returns if price holds.</span>
            </p>
            <p className="text-sm text-white/40 leading-relaxed">
              LP-D earns its configured share of pool fees. The USDC collateral is only drawn if the LP
              exits while price has moved significantly. If price reverts — or barely moved
              — the LP-D holder keeps their collateral and earned fees. It is an option
              premium model: collect income, pay out only when the event occurs.
            </p>
            <div className="mt-6 flex gap-2">
              <span className="rounded-full border border-violet-500/20 bg-violet-500/5 px-3 py-1 text-xs text-violet-400">
                fee share (configurable)
              </span>
              <span className="rounded-full border border-violet-500/20 bg-violet-500/5 px-3 py-1 text-xs text-violet-400">
                collateral returned on revert
              </span>
            </div>
          </div>
        </div>

        <p className="mt-12 text-center text-sm text-white/30 max-w-2xl mx-auto leading-relaxed">
          Both sides earn under normal conditions. The hook does not redistribute losses —
          it separates risk at the point of deposit so each party holds only what they priced in.
        </p>
      </div>
    </section>
  )
}
